language: node_js
node_js:
  - "6"
script: npm test
notifications:
  slack:
    on_success: change
    secure: hrHHOdIuPznKPbT2nRMfd9Z3l7eMb/ibaTsGYhX+RJPXvMqju0uVOXNdU1PuonFaEo7/i0/g4crXb3Py/PT1Q0nZA8JIDWpUd2rt1uIQ5QD8fwG9b9K39DUpULe6LBL67ZZ6kB0oRExS7PpWADRnUBD3NC/YyM+sc6rS5EG954x3LiErqAD3Q6+m/XBFQB8ffXwlg3k4bEScruENaJGf+UxZIyo1XJ3aK6ctzdHJFr3XlU1auYF4eETRgL7b2ao/VxSGMxY5dL8rHQ0FWDCUkkO3QuSmmi2kabcSCh9LvbfPqkNzUAdd/Qz0bQcxeb0uxn7Y7C+EoB4Ugod34morDZcZNOrtthkEgcC6HtHPJbU3tJVD0I9p+f7WGbl/6S4H4K4fTIyzSQ5viIzZS5Kt4+uey9EmulBORvv1ICGmUnTQQ60hY8VWbR93kyVNfXxRma6PcuDQ23gfITuk6fwngeVTchxk5ea+zK7y4vfm5tEUHI3DeN7qVhJ3phmihWrMTwGDLgeIIDAvdbs+oH4zYKPjsEs1E1IEixhQ8eETOiiS0lglVT0vWt2moX2AbeEKoIoNryG3LkWlfT+vuzn1dfJV9HsBaacORiFwuoovtrwIQo0QXcj3UNqZdYv+fhu1wUMU0kzU75pfPJQrm5T/zAPcQYoam2tiDvgHbCACirA=
